[[redirects]]
  from = "/home"
  to = "/currently/"
  status = 301

[[redirects]]
  from = "/experiments"
  to = "/ux/"
  status = 301

[[redirects]]
  from = "/skins"
  to = "/qnx/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200